apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-demo
  labels:
    app: java-app-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-app-demo
  template:
    metadata:
      labels:
        app: java-app-demo
    spec:
      containers:
      - name: java-app
        image: 19980617/e2ebuild:38
        ports:
        - containerPort: 8080

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: python-app-blue
#   labels:
#     app: python-app-demo
#     version: blue
#   annotations:
#     harness.io/direct-apply: "true"  # Allow direct deployment without Blue-Green logic
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: python-app-demo
#       version: blue
#   template:
#     metadata:
#       labels:
#         app: python-app-demo
#         version: blue
#     spec:
#       containers:
#       - name: python-app
#         image: harithahari2420/java-ci-harness:wc0ZQwufRsSO3uqGWd8Rkw
#         ports:
#         - containerPort: 8080

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: python-app-green
#   labels:
#     app: python-app-demo
#     version: green
#   annotations:
#     harness.io/direct-apply: "true"  # Allow direct deployment without Blue-Green logic
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: python-app-demo
#       version: green
#   template:
#     metadata:
#       labels:
#         app: python-app-demo
#         version: green
#     spec:
#       containers:
#       - name: python-app
#         image: harithahari2420/java-ci-harness:RPoI86qPToampW-DZU7fLw
#         ports:
#         - containerPort: 8080
