# apiVersion: v1
# kind: Service
# metadata:
#   name: java-app-service
# spec:
#   type: NodePort
#   selector:
#     app: java-app-demo
#   ports:
#     - name: http
#       protocol: TCP
#       port: 80
#       targetPort: 8080
#       nodePort: 30007

apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer
  selector:
    app: python-app-demo
    version: blue   # Change to 'green' when switching traffic
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
